# Generated by Django 5.2.1 on 2025-06-02 10:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='otpverification',
            options={'verbose_name': 'OTP Verification', 'verbose_name_plural': 'OTP Verifications'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='image',
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_details',
            field=models.TextField(blank=True, help_text='Specific location details within the platform', null=True, verbose_name='Location Details'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Complaint Number'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='Issue Description'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='platform_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Platform Number'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reporter_name',
            field=models.CharField(max_length=100, verbose_name='Reporter Name'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reporter_phone',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.station', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Attempts'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint', verbose_name='Complaint'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=6, verbose_name='OTP'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Station Name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Station Code'),
        ),
        migrations.CreateModel(
            name='ComplaintPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='complaints/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Photo',
                'verbose_name_plural': 'Complaint Photos',
            },
        ),
    ]
