# Generated by Django 5.2.1 on 2025-06-02 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Type')),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
            },
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='location_details',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='platform_number',
        ),
        migrations.AddField(
            model_name='station',
            name='total_platforms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Platforms'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_code',
            field=models.CharField(max_length=10, verbose_name='Station Code'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='City Code')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_cities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='complaints.city'),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('station_code', 'city')},
        ),
        migrations.CreateModel(
            name='PlatformLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Platform Number')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.locationtype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_locations', to='complaints.station')),
            ],
            options={
                'verbose_name': 'Platform Location',
                'verbose_name_plural': 'Platform Locations',
                'unique_together': {('station', 'platform_number', 'location_type')},
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='platform_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.platformlocation', verbose_name='Platform Location'),
        ),
    ]
