# Generated by Django 5.2.1 on 2025-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_locationtype_remove_complaint_location_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_worker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned Worker'),
        ),
    ]
