# Generated by Django 5.2.1 on 2025-06-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_station_created_at_station_manager_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationtype',
            options={'verbose_name': 'Location Type (Deprecated)', 'verbose_name_plural': 'Location Types (Deprecated)'},
        ),
        migrations.AlterUniqueTogether(
            name='platformlocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='platformlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='platformlocation',
            name='location_description',
            field=models.CharField(default='General Area', help_text='Custom description of the location (e.g., "Near Ticket Counter", "Platform Entry", "Waiting Area")', max_length=200, verbose_name='Location Description'),
        ),
        migrations.AlterField(
            model_name='platformlocation',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.locationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='platformlocation',
            unique_together={('station', 'platform_number', 'location_description')},
        ),
    ]
