# Generated by Django 5.2.1 on 2025-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_add_custom_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformlocation',
            name='hash_id',
            field=models.IntegerField(default=1, help_text='Consecutive ID for this platform location', verbose_name='Hash ID'),
        ),
    ]
