# Generated by Django 5.2.1 on 2025-06-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_add_hash_id_to_platform_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformlocation',
            name='hash_id',
        ),
    ]
