# Generated by Django 5.2.1 on 2025-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_remove_platformlocation_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Issue Description'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reporter Name'),
        ),
    ]
