# Generated by Django 5.2.1 on 2025-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_complaint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformlocation',
            name='hash_id',
            field=models.CharField(blank=True, help_text='Format: P[platform][sequence] (e.g., P11, P12, P21)', max_length=10, verbose_name='Hash ID'),
        ),
    ]
