# Generated by Django 5.2.1 on 2025-06-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_add_parent_child_complaint_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.IntegerField(default=1, help_text='Number of duplicate scan attempts', verbose_name='Attempt Count')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, verbose_name='Last Attempt At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('reporter_phones', models.TextField(blank=True, help_text='Comma-separated list of phone numbers that attempted', verbose_name='Reporter Phones')),
                ('original_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_scan_attempts', to='complaints.complaint')),
                ('platform_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_attempts', to='complaints.platformlocation')),
            ],
            options={
                'verbose_name': 'QR Scan Attempt',
                'verbose_name_plural': 'QR Scan Attempts',
                'unique_together': {('platform_location', 'original_complaint')},
            },
        ),
    ]
