# Generated by Django 5.2.1 on 2025-06-05 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_add_qr_scan_attempt_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformlocation',
            name='hash_id',
            field=models.CharField(blank=True, help_text='Format: (Platform Number/QR Number) (e.g., (1/1), (1/2), (2/1))', max_length=15, verbose_name='Hash ID'),
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100, verbose_name='Manager Name')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='Manager Email')),
                ('manager_phone', models.CharField(max_length=15, verbose_name='Manager Phone')),
                ('issue_category', models.CharField(choices=[('login_access', 'Login/Access Issues'), ('complaint_management', 'Complaint Management'), ('qr_codes', 'QR Code Issues'), ('reports_analytics', 'Reports & Analytics'), ('system_performance', 'System Performance'), ('training_help', 'Training & Help'), ('other', 'Other')], max_length=50, verbose_name='Issue Category')),
                ('priority', models.CharField(choices=[('low', 'Low - General inquiry'), ('medium', 'Medium - System issue affecting work'), ('high', 'High - Urgent issue affecting operations'), ('critical', 'Critical - System down/emergency')], max_length=20, verbose_name='Priority')),
                ('issue_description', models.TextField(verbose_name='Issue Description')),
                ('steps_to_reproduce', models.TextField(blank=True, null=True, verbose_name='Steps to Reproduce')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned To')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
